# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manage', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('log_type', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=225)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=125)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
