# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_auto_20180526_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=225)),
                ('log_type', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'config',
            },
        ),
    ]
